force-apps/dreamhouse_ELTOROit/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/dreamhouse_ELTOROit/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Asking Price</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-apps/deploy/main/default/objects/PropertyPriceHistory__c/PropertyPriceHistory__c.object-meta.xml
<CustomObject>
    <description>This object contains the history of the prices for each property</description>
    <label>Property Price History</label>
    <nameField>
        <displayFormat>HIST-{0000}</displayFormat>
        <label>PriceHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Prices History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/PropertyPriceHistory__c/fields/DateChanged__c.field-meta.xml
<CustomField>
    <fullName>DateChanged__c</fullName>
    <label>Date Changed</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-apps/deploy/main/default/objects/PropertyPriceHistory__c/fields/NewPrice__c.field-meta.xml
<CustomField>
    <fullName>NewPrice__c</fullName>
    <label>New Price</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-apps/deploy/main/default/objects/PropertyPriceHistory__c/fields/OldPrice__c.field-meta.xml
<CustomField>
    <fullName>OldPrice__c</fullName>
    <label>Old Price</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-apps/deploy/main/default/objects/PropertyPriceHistory__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Price Histories</relationshipLabel>
    <relationshipName>PriceHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-apps/deploy/main/default/classes/ETDH_PropertyPriceHistory.cls
public with sharing class ETDH_PropertyPriceHistory {
	@InvocableMethod(label='ETDH: Property Price History' description='Retrieve price history information for a property')
	public static List<AgentResult> getHistory(List<AgentRequest> requests) {
		List<AgentResult> results = new List<AgentResult>();

		for (AgentRequest request : requests) {
			results.add(getHistory(request));
		}
		return results;
	}

	private static AgentResult getHistory(AgentRequest request) {
		AgentResult result = new AgentResult();
 
		try {
			result.error = null;
			result.priceChanges = [
				SELECT Id, (SELECT Id, DateChanged__c, OldPrice__c, NewPrice__c FROM PropertyPricesHistory__r ORDER BY DateChanged__c DESC)
				FROM Property__c
				WHERE ID = :request.PropertyID
			]
			.PropertyPricesHistory__r;
		} catch (Exception e) {
			System.debug(e.getMessage());
			result.error = 'An error has occurred' + e.getMessage() + '\n' + e.getStackTraceString() + '\n' + e.getLineNumber();
		}
		return result;
	}

	// Handles the changes to the property prices, invoked from before update trigger
	public static void updatePriceHistory(List<Property__c> newProperties, Map<Id, Property__c> oldProperties) {
		List<PropertyPriceHistory__c> phs = new List<PropertyPriceHistory__c>();
		for (Property__c newProperty : newProperties) {
			Property__c oldProperty = new Property__c();
			if (oldProperties != null) {
				oldProperty = oldProperties.get(newProperty.Id);
			}
			if (newProperty.Price__c != oldProperty.Price__c) {
				PropertyPriceHistory__c ph = new PropertyPriceHistory__c();
				ph.Property__c = newProperty.Id;
				ph.OldPrice__c = oldProperty.Price__c;
				ph.NewPrice__c = newProperty.Price__c;
				ph.DateChanged__c = System.now();
				phs.add(ph);
			}
		}

		if (phs.size() > 0) {
			insert phs;
		}
	}

	public class AgentRequest {
		@InvocableVariable(required=true description='Property ID of th eproperty to get the price history for')
		public ID PropertyID;
	}

	public class AgentResult {
		@InvocableVariable(required=false description='List of price changes')
		public List<PropertyPriceHistory__c> priceChanges;
		@InvocableVariable(required=false description='Error message')
		public String error;
	}
}