force-apps/dreamhouse_ELTOROit/main/default/objects/PriceHistory__c/PriceHistory__c.object-meta.xml
<CustomObject>
    <description>...</description>
    <label>Price History</label>
    <nameField>
        <displayFormat>Price-{0000}</displayFormat>
        <label>Price History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-apps/dreamhouse_ELTOROit/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/dreamhouse_ELTOROit/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Asking Price</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-apps/deploy/main/default/objects/Property__c/fields/PriceHistory__c.field-meta.xml
<CustomField>
    <fullName>PriceHistory__c</fullName>
    <label>Price History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-apps/dreamhouse_ELTOROit/main/default/classes/ETDH_PropertyPriceHistory.cls
public with sharing class ETDH_PropertyPriceHistory {
	public static void updatePriceHistory(List<Property__c> newProperties, Map<Id, Property__c> oldProperties) {
		List<PriceHistory__c> phs = new List<PriceHistory__c>();
		for (Property__c newProperty : newProperties) {
			Property__c oldProperty = new Property__c();
			if (oldProperties != null) {
				oldProperty = oldProperties.get(newProperty.Id);
			}
			if (newProperty.Price__c != oldProperty.Price__c) {
				PriceHistory__c ph = new PriceHistory__c();
				ph.Property__c = newProperty.Id;
				ph.OldPrice__c = oldProperty.Price__c;
				ph.NewPrice__c = newProperty.Price__c;
				ph.DateChanged__c = System.now();
				phs.add(ph);
			}
		}

		if (phs.size() > 0) {
			insert phs;
		}
	}
}